- agent/utils/utils.go
When the agent sends a request to the proxy server, it includes an
OAuth access token in the 'Authorization' header to identify itself.
Previously, that token was being generated as soon as the agent had
a request to forward to the backend server. However, that token was
only guaranteed to be valid for 10 seconds, and the backend server
could take longer than that to respond.
This allowed a scenario where the OAuth access token would expire
between the time the request to the proxy was generated and the
time when it was actually sent to the proxy server.
This commit fixes that issue by delaying the proxy request round
trip until we know that the request has enough data to be sent
to the proxy server. This amounts to the response from the backend
server either having some of its body …
> Fix a potential race condition with agent credentials.

- agent/agent.go
- agent/utils/utils.go
This change adds a new header in the requests that the agent sends to the
proxy. That header is used to report the identity of the host VM for the
scenario that the agent is running inside of a Google Compute Engine VM.
When running outside of Google Compute Engine, this change is a no-op.
This change also cleaned up existing lint issues in the agent.
> Report VM identity (if available) to the proxy.

- agent/Dockerfile
This change extends the options for the recently added health-checking
feature to the Dockerfile used for packaging the proxy agent.
> Expose the health-checking options through the Dockerfile.

- agent/agent.go
This commit sets a timeout in the HTTP client used by the agent, addressing #4 .
> Set a timeout in the HTTP client used by the agent

- agent/agent_test.go
The previous package name was `agent`, however, the package name in
the `agent.go` file is `main`. This mismatch causes issues if you try
to run `go build github.com/google/inverting-proxy/agent`.
With this updated version, the `go build ...` command will work.
> Fix the package name for the `agent_test.go` file.

- agent/websockets/shim.go
Data sent via websockets are supposed to be sent in-order, but the
previous version of the client-side code for the websocket shim sent
all messages asynchronously, which could cause them to be received
out of order by the agent.
This change adds an array for storing the websocket data to be sent,
and has the client-side JS code work through this array in sequence.
Thanks to @zainrizvi for finding this bug and tracking it down to the root cause.
> agent: maintain ordering of the shimmed websocket messages

- Makefile
- testing/runlocal/main.go
- testing/websockets/main.go
This change builds on top of the new server binary to make it easy
to test an end-to-end inverting proxy/agent/backend setup locally.
That, in turn, makes it much easier to manually test changes to
either the agent or the server binary.
> Add a helper command for running an inverting proxy and agent locally

- server/server.go
This change fixes a bug in the locally-runnable version of the
inverting proxy where the headers from a proxied response were not
copied in to the response sent back to the frontend client.
That prevents things like set-cookie from working when testing local
changes.
That, in turn, was blocking the testing of a fix to
https://github.com/google/inverting-proxy/issues/31
> Fix a bug in the locally-runnable proxy where headers were not copied

- agent/agent.go
- agent/utils/utils.go
This functionality is currently broken for GKE deployments, so for now turn this off with a flag.
> Add flag to turn off adding GCE VM headers

- agent/websockets/connection.go
- agent/websockets/shim.go
This change fixes a bug in the agent where request headers from websocket-shim open requests were not being copied into the websocket upgrade request forwarded to the backend server.
Fixes #43
> agent: add request headers to new websocket connections

- agent/agent.go
- agent/banner/banner.go
1. Disable caching for the injected banner page. This prevents a bug
where the client would simply show the banner twice instead of the
banner and the iframe-ed backend page.
2. Fix the height of the iframe to be the page height minus the height
of the banner. This requires the agent to know how tall the banner
can be, so we also add another command line flag to specify that.
> Fix two bugs in the agent banner injection feature

- Makefile
- agent/websockets/connection.go
- agent/websockets/shim.go
- testing/websockets/example/main.go
This PR extends the websocket-shim to support sending and receiving binary
messages over the shimmed WebSocket connections.
The WebSocket-over-HTTP protocol is extended such that messages
returned by the `poll` handler may be either a string (for text
messages), or an array of a single string (for binary messages). This is
intentionally backwards-compatible with the previous version of the
protocol, so any proxies implementing the shim layer in the proxy will
still work with the updated agent.
The shim code detects this difference between the possible types
and uses it to determine whether to emit an event with a string,
or an event with a Blob (which is constructed directly from the
array of the single string).
This was tested in two ways:
1. By running a proxy and agent with websocket …
> Add support for binary WebSocket messages.

- agent/banner/banner.go
This change makes sure that the browser displayed url and history are consistent with the iframe state.
Also adds an id field to the wrapper iframe to make Selenium testing easier
> Make window url and history consistent when banner injection enabled

- agent/banner/banner.go
Before this fix, the favicon logic was active when the flag was unset. This broke all requests with the banner enabled.
> Fix bug in favicon url logic

- agent/websockets/connection.go
This fixes a consistent deadlock which is causing web socket connections to leak:
- serverConn.ReadMessage() waits on the connection to be closed.
- The code  waits on serverConn.ReadMessage to finish before it calls serverConn.Close()
> Close Web Socket Connections

- agent/websockets/shim.go
https://github.com/google/inverting-proxy/commit/38b2d0860e833d43ecd1eddb1ac4848751e01b3a#diff-0330ef20b91a1cecda3048ce7c570cd7R295
The change is causing failure on the backend service validating the true origin of the call
> Revert the Origin header setting logic

- agent/sessions/sessions.go
- agent/sessions/sessions_test.go
This addresses an edge condition where the session is never created.
> Switch order of session creation and new cookie check.

- agent/banner/banner.go
- agent/banner/banner_test.go
As of Chrome 80, requests from iframes appear to arrive with Sec-Fetch-Mode: 'navigate' and Sec-Fetch-Dest: 'iframe', instead of the previous behavior of Sec-Fetch-Mode: 'nested-navigate' and Sec-Fetch-Dest: 'document.'
Adding this check allows to correctly handle either behavior.
> Improve detection of already framed pages

- agent/agent.go
- agent/websockets/shim.go
- testing/websockets/main.go
… connection
This change is gated behind the flag --rewrite-websocket-host
> Rewrite host header to original request host when opening a websocket connection

- agent/agent.go
- agent/websockets/shim.go
- testing/websockets/main.go
This fixes an edge condition where cookies with path
restrictions are not sent when opening a websocket connection
because the path is `websocket-shim/open` when the session is restored.
This change brings the cookie handler downstream of the websocket
handler for non-shimmed requests, and restores cookies for
websocket open requests based on the correct path.
> Swap order of websocket and session handlers

- agent/Dockerfile
- Variables required for Dataproc Hub. Default to "silent" values.
- Actual values sets through an env file.
- Those variables used to be passed through the string value of HEALTH_CHECK_UNHEALTHY_THRESHOLD.
> Adding standalone env variables for Dataproc Hub

- agent/websockets/connection.go
Stop stripping the `Sec-WebSocket-Protocol` header from websocket upgrade requests to support application-level websocket subprotocols.
> Support passing an application subprotocol to the backend

- agent/agent.go
This new debug line will display HTTP requests that arrive from Proxy. Example: Saving a Notebook generates a PUT request and is relevant to be able to see it here.
Tested:
```
{"log":"2021/04/04 22:45:18 Request 005e38f07710c29e15d1e8943374ed969aab7d1d08fd708b39594ad6b309bbd90dc19fe3e0dbf0a7f10d103531f2a4f1dfaa
f8927447e05fe5bc62ad9d2b1d97e6c6e80fa0365cf5f91208811798b81643568815d0c0e265cc11a9ba15f9991211d4ce80210500b2f21dcd9ac79d29d910b5b5ddee9f
e758a2ecc5f632400a31: PUT 70efaed9f61f7d8f-dot-us-central1.notebooks.googleusercontent.com 30150937\n","stream":"stderr","time":"2021-04
-04T22:45:18.203076885Z"}
```
> Display HTTP Requests if debug is enabled

- README.md
This change adds a note to the README that the inverting proxy does not currently work with IAP.
> Note that we do not currently support IAP

- agent/utils/utils.go
- agent/utils/utils_test.go
The retries are supposed to overcome transient network connectivity errors and other internal server errors when reading request or writing response.
> Add retries to read request and write response calls to proxy

- agent/agent.go
- agent/agent_test.go
- agent/utils/utils.go
- Add a new optional (via flag) feature for enabling gracefully shutting down the agent
- We should stop pulling new requests and drain the already pulled/being processed ones during the graceful shutdown time window. Basically the agent should act in a "lame duck" mode when received a shutdown signal from the OS.
Issue #100
> Gracefully shutdown the agent

- .gitignore
- app/agent.yaml
- app/api.yaml
- app/app.yaml
- app/proxy.go
- app/proxy/cache.go
- app/proxy/store.go
- app/proxy/types.go
- go.mod
- go.sum
The old `go1` runtime that was previously used is no longer supported, and so the AppEngine version of the proxy was no longer usable.
A previous change tried to fix that by upgrading to the latest `go116` version, but simply upgrading was not sufficient as the new runtime is not backwards compatible to the older runtime.
This change finishes the migration to `go116`, which required restructuring the app. I followed the guide [here](https://cloud.google.com/appengine/docs/standard/go/go-differences) to do that restructuring.
Additionally, I've removed the usage of the legacy AppEngine logging package, and switched the usages of `context` over to the version in the standard library.
> Update the AppEngine version of the proxy to the latest Go runtime

- agent/sessions/sessions.go
- agent/utils/utils_test.go
- app/proxy.go
- server/server.go
- testing/runlocal/main.go
- testing/websockets/example/main.go
- testing/websockets/main.go
The included changes were generated by running the `make test` command in the root directory, which in turn runs `gofmt -w`
> Fix formatting in golang files that were misformatted

- agent/agent.go
- agent/utils/utils.go
- agent/utils/utils_test.go
Previously, the HTTP response forwarded by the proxy agent to the
proxy had a hard-coded proto of "HTTP/1.1".
With this change, it will instead use a proto that matches the
request received by the agent from the proxy.
> Support the HTTP/2 proto for response forwarding.

- agent/Dockerfile
curl uses a MIT license vs wget uses GPL
> Update Dockerfile to use curl vs wget

- agent/utils/utils.go
- agent/utils/utils_test.go
When a request is cancelled prior to the response being written, we might still get a response from the backend and try to write it.
Previously, if that happened the write of the response body would hang forever, waiting for the response to be serialized to the no-longer extant proxy request.
With this change, that no longer happens because we catch this scenario in the `WriteHeader` method and close the body reader... causing any subsequent writes to immediately fail.
> [agent] Fix a race condition when writing a response to a cancelled request.

- agent/Dockerfile
Upgrade the go version to handle security vulnerabilities.
> Upgrading go version mainly for security fixes

- agent/websockets/shim.go
After extensive testing we found that the connections map hosting correct setup of connections:
$ docker logs  ba-proxy-agent 2>&1 | grep "attempt to read data from a closed session" | wc
2479   27269  174902
$ docker logs -f ba-proxy-agent --tail 10
2024/09/26 10:57:28 Websocket connection to the server "ws://localhost:8094/websocket-shim/" established for session: 3141
, total sessions: 662
2024/09/26 10:57:28 Websocket connection to the server "ws://localhost:8094/websocket-shim/" established for session: 3143
, total sessions: 663
2024/09/26 10:57:28 Websocket connection to the server "ws://localhost:8094/websocket-shim/" established for session: 3142
, total sessions: 664
2024/09/26 10:57:28 Websocket connection to the server "ws://localhost:8094/websocket-shim/" established for …
> Deleting closed connections from the connections map

- agent/websockets/connection.go
Fix a bug where the agent would leak goroutines when a websocket connection is closed.
This was caused by the logic that coordinates reading and writing to the websocket connection to be too complicated, and using a channel for communicating when to exit instead of just cancelling the context.
The use of that (unbuffered) channel then caused a leak when two separate goroutines both tried to send a message to the channel, but only one read was ever performed, and as a result the second goroutine would always hang indefinitely.
This leak and the corresponding fix were confirmed using manual testing.
This change also fixes a bad coding pattern where we stored the context in a struct. Instead, we just store the methods from that context that are actually needed.
> [agent] Fix a goroutine leak that happens when a websocket connection is closed.
